// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/stinger-batch.proto

#ifndef PROTOBUF_src_2fproto_2fstinger_2dbatch_2eproto__INCLUDED
#define PROTOBUF_src_2fproto_2fstinger_2dbatch_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gt {
namespace stinger {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_src_2fproto_2fstinger_2dbatch_2eproto();
void protobuf_AssignDesc_src_2fproto_2fstinger_2dbatch_2eproto();
void protobuf_ShutdownFile_src_2fproto_2fstinger_2dbatch_2eproto();

class EdgeInsertion;
class EdgeDeletion;
class StingerBatch;

// ===================================================================

class EdgeInsertion : public ::google::protobuf::Message {
 public:
  EdgeInsertion();
  virtual ~EdgeInsertion();

  EdgeInsertion(const EdgeInsertion& from);

  inline EdgeInsertion& operator=(const EdgeInsertion& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EdgeInsertion& default_instance();

  void Swap(EdgeInsertion* other);

  // implements Message ----------------------------------------------

  EdgeInsertion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EdgeInsertion& from);
  void MergeFrom(const EdgeInsertion& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 source = 1 [default = 0];
  inline bool has_source() const;
  inline void clear_source();
  static const int kSourceFieldNumber = 1;
  inline ::google::protobuf::int64 source() const;
  inline void set_source(::google::protobuf::int64 value);

  // optional string source_str = 2 [default = ""];
  inline bool has_source_str() const;
  inline void clear_source_str();
  static const int kSourceStrFieldNumber = 2;
  inline const ::std::string& source_str() const;
  inline void set_source_str(const ::std::string& value);
  inline void set_source_str(const char* value);
  inline void set_source_str(const char* value, size_t size);
  inline ::std::string* mutable_source_str();
  inline ::std::string* release_source_str();
  inline void set_allocated_source_str(::std::string* source_str);

  // optional int64 destination = 3 [default = 1];
  inline bool has_destination() const;
  inline void clear_destination();
  static const int kDestinationFieldNumber = 3;
  inline ::google::protobuf::int64 destination() const;
  inline void set_destination(::google::protobuf::int64 value);

  // optional string destination_str = 4 [default = ""];
  inline bool has_destination_str() const;
  inline void clear_destination_str();
  static const int kDestinationStrFieldNumber = 4;
  inline const ::std::string& destination_str() const;
  inline void set_destination_str(const ::std::string& value);
  inline void set_destination_str(const char* value);
  inline void set_destination_str(const char* value, size_t size);
  inline ::std::string* mutable_destination_str();
  inline ::std::string* release_destination_str();
  inline void set_allocated_destination_str(::std::string* destination_str);

  // optional int64 weight = 5 [default = 1];
  inline bool has_weight() const;
  inline void clear_weight();
  static const int kWeightFieldNumber = 5;
  inline ::google::protobuf::int64 weight() const;
  inline void set_weight(::google::protobuf::int64 value);

  // optional int64 time = 6 [default = 1];
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 6;
  inline ::google::protobuf::int64 time() const;
  inline void set_time(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:gt.stinger.EdgeInsertion)
 private:
  inline void set_has_source();
  inline void clear_has_source();
  inline void set_has_source_str();
  inline void clear_has_source_str();
  inline void set_has_destination();
  inline void clear_has_destination();
  inline void set_has_destination_str();
  inline void clear_has_destination_str();
  inline void set_has_weight();
  inline void clear_has_weight();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 source_;
  ::std::string* source_str_;
  ::google::protobuf::int64 destination_;
  ::std::string* destination_str_;
  ::google::protobuf::int64 weight_;
  ::google::protobuf::int64 time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_src_2fproto_2fstinger_2dbatch_2eproto();
  friend void protobuf_AssignDesc_src_2fproto_2fstinger_2dbatch_2eproto();
  friend void protobuf_ShutdownFile_src_2fproto_2fstinger_2dbatch_2eproto();

  void InitAsDefaultInstance();
  static EdgeInsertion* default_instance_;
};
// -------------------------------------------------------------------

class EdgeDeletion : public ::google::protobuf::Message {
 public:
  EdgeDeletion();
  virtual ~EdgeDeletion();

  EdgeDeletion(const EdgeDeletion& from);

  inline EdgeDeletion& operator=(const EdgeDeletion& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EdgeDeletion& default_instance();

  void Swap(EdgeDeletion* other);

  // implements Message ----------------------------------------------

  EdgeDeletion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EdgeDeletion& from);
  void MergeFrom(const EdgeDeletion& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 source = 1 [default = 0];
  inline bool has_source() const;
  inline void clear_source();
  static const int kSourceFieldNumber = 1;
  inline ::google::protobuf::int64 source() const;
  inline void set_source(::google::protobuf::int64 value);

  // optional string source_str = 2 [default = ""];
  inline bool has_source_str() const;
  inline void clear_source_str();
  static const int kSourceStrFieldNumber = 2;
  inline const ::std::string& source_str() const;
  inline void set_source_str(const ::std::string& value);
  inline void set_source_str(const char* value);
  inline void set_source_str(const char* value, size_t size);
  inline ::std::string* mutable_source_str();
  inline ::std::string* release_source_str();
  inline void set_allocated_source_str(::std::string* source_str);

  // optional int64 destination = 3 [default = 1];
  inline bool has_destination() const;
  inline void clear_destination();
  static const int kDestinationFieldNumber = 3;
  inline ::google::protobuf::int64 destination() const;
  inline void set_destination(::google::protobuf::int64 value);

  // optional string destination_str = 4 [default = ""];
  inline bool has_destination_str() const;
  inline void clear_destination_str();
  static const int kDestinationStrFieldNumber = 4;
  inline const ::std::string& destination_str() const;
  inline void set_destination_str(const ::std::string& value);
  inline void set_destination_str(const char* value);
  inline void set_destination_str(const char* value, size_t size);
  inline ::std::string* mutable_destination_str();
  inline ::std::string* release_destination_str();
  inline void set_allocated_destination_str(::std::string* destination_str);

  // @@protoc_insertion_point(class_scope:gt.stinger.EdgeDeletion)
 private:
  inline void set_has_source();
  inline void clear_has_source();
  inline void set_has_source_str();
  inline void clear_has_source_str();
  inline void set_has_destination();
  inline void clear_has_destination();
  inline void set_has_destination_str();
  inline void clear_has_destination_str();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 source_;
  ::std::string* source_str_;
  ::google::protobuf::int64 destination_;
  ::std::string* destination_str_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_src_2fproto_2fstinger_2dbatch_2eproto();
  friend void protobuf_AssignDesc_src_2fproto_2fstinger_2dbatch_2eproto();
  friend void protobuf_ShutdownFile_src_2fproto_2fstinger_2dbatch_2eproto();

  void InitAsDefaultInstance();
  static EdgeDeletion* default_instance_;
};
// -------------------------------------------------------------------

class StingerBatch : public ::google::protobuf::Message {
 public:
  StingerBatch();
  virtual ~StingerBatch();

  StingerBatch(const StingerBatch& from);

  inline StingerBatch& operator=(const StingerBatch& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StingerBatch& default_instance();

  void Swap(StingerBatch* other);

  // implements Message ----------------------------------------------

  StingerBatch* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StingerBatch& from);
  void MergeFrom(const StingerBatch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 version = 1 [default = 1];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int64 version() const;
  inline void set_version(::google::protobuf::int64 value);

  // repeated .gt.stinger.EdgeInsertion insertions = 3;
  inline int insertions_size() const;
  inline void clear_insertions();
  static const int kInsertionsFieldNumber = 3;
  inline const ::gt::stinger::EdgeInsertion& insertions(int index) const;
  inline ::gt::stinger::EdgeInsertion* mutable_insertions(int index);
  inline ::gt::stinger::EdgeInsertion* add_insertions();
  inline const ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeInsertion >&
      insertions() const;
  inline ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeInsertion >*
      mutable_insertions();

  // repeated .gt.stinger.EdgeDeletion deletions = 4;
  inline int deletions_size() const;
  inline void clear_deletions();
  static const int kDeletionsFieldNumber = 4;
  inline const ::gt::stinger::EdgeDeletion& deletions(int index) const;
  inline ::gt::stinger::EdgeDeletion* mutable_deletions(int index);
  inline ::gt::stinger::EdgeDeletion* add_deletions();
  inline const ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeDeletion >&
      deletions() const;
  inline ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeDeletion >*
      mutable_deletions();

  // @@protoc_insertion_point(class_scope:gt.stinger.StingerBatch)
 private:
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 version_;
  ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeInsertion > insertions_;
  ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeDeletion > deletions_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_src_2fproto_2fstinger_2dbatch_2eproto();
  friend void protobuf_AssignDesc_src_2fproto_2fstinger_2dbatch_2eproto();
  friend void protobuf_ShutdownFile_src_2fproto_2fstinger_2dbatch_2eproto();

  void InitAsDefaultInstance();
  static StingerBatch* default_instance_;
};
// ===================================================================


// ===================================================================

// EdgeInsertion

// optional int64 source = 1 [default = 0];
inline bool EdgeInsertion::has_source() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EdgeInsertion::set_has_source() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EdgeInsertion::clear_has_source() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EdgeInsertion::clear_source() {
  source_ = GOOGLE_LONGLONG(0);
  clear_has_source();
}
inline ::google::protobuf::int64 EdgeInsertion::source() const {
  return source_;
}
inline void EdgeInsertion::set_source(::google::protobuf::int64 value) {
  set_has_source();
  source_ = value;
}

// optional string source_str = 2 [default = ""];
inline bool EdgeInsertion::has_source_str() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EdgeInsertion::set_has_source_str() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EdgeInsertion::clear_has_source_str() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EdgeInsertion::clear_source_str() {
  if (source_str_ != &::google::protobuf::internal::kEmptyString) {
    source_str_->clear();
  }
  clear_has_source_str();
}
inline const ::std::string& EdgeInsertion::source_str() const {
  return *source_str_;
}
inline void EdgeInsertion::set_source_str(const ::std::string& value) {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  source_str_->assign(value);
}
inline void EdgeInsertion::set_source_str(const char* value) {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  source_str_->assign(value);
}
inline void EdgeInsertion::set_source_str(const char* value, size_t size) {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  source_str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EdgeInsertion::mutable_source_str() {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  return source_str_;
}
inline ::std::string* EdgeInsertion::release_source_str() {
  clear_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = source_str_;
    source_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void EdgeInsertion::set_allocated_source_str(::std::string* source_str) {
  if (source_str_ != &::google::protobuf::internal::kEmptyString) {
    delete source_str_;
  }
  if (source_str) {
    set_has_source_str();
    source_str_ = source_str;
  } else {
    clear_has_source_str();
    source_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 destination = 3 [default = 1];
inline bool EdgeInsertion::has_destination() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EdgeInsertion::set_has_destination() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EdgeInsertion::clear_has_destination() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EdgeInsertion::clear_destination() {
  destination_ = GOOGLE_LONGLONG(1);
  clear_has_destination();
}
inline ::google::protobuf::int64 EdgeInsertion::destination() const {
  return destination_;
}
inline void EdgeInsertion::set_destination(::google::protobuf::int64 value) {
  set_has_destination();
  destination_ = value;
}

// optional string destination_str = 4 [default = ""];
inline bool EdgeInsertion::has_destination_str() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EdgeInsertion::set_has_destination_str() {
  _has_bits_[0] |= 0x00000008u;
}
inline void EdgeInsertion::clear_has_destination_str() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void EdgeInsertion::clear_destination_str() {
  if (destination_str_ != &::google::protobuf::internal::kEmptyString) {
    destination_str_->clear();
  }
  clear_has_destination_str();
}
inline const ::std::string& EdgeInsertion::destination_str() const {
  return *destination_str_;
}
inline void EdgeInsertion::set_destination_str(const ::std::string& value) {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  destination_str_->assign(value);
}
inline void EdgeInsertion::set_destination_str(const char* value) {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  destination_str_->assign(value);
}
inline void EdgeInsertion::set_destination_str(const char* value, size_t size) {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  destination_str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EdgeInsertion::mutable_destination_str() {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  return destination_str_;
}
inline ::std::string* EdgeInsertion::release_destination_str() {
  clear_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = destination_str_;
    destination_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void EdgeInsertion::set_allocated_destination_str(::std::string* destination_str) {
  if (destination_str_ != &::google::protobuf::internal::kEmptyString) {
    delete destination_str_;
  }
  if (destination_str) {
    set_has_destination_str();
    destination_str_ = destination_str;
  } else {
    clear_has_destination_str();
    destination_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 weight = 5 [default = 1];
inline bool EdgeInsertion::has_weight() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void EdgeInsertion::set_has_weight() {
  _has_bits_[0] |= 0x00000010u;
}
inline void EdgeInsertion::clear_has_weight() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void EdgeInsertion::clear_weight() {
  weight_ = GOOGLE_LONGLONG(1);
  clear_has_weight();
}
inline ::google::protobuf::int64 EdgeInsertion::weight() const {
  return weight_;
}
inline void EdgeInsertion::set_weight(::google::protobuf::int64 value) {
  set_has_weight();
  weight_ = value;
}

// optional int64 time = 6 [default = 1];
inline bool EdgeInsertion::has_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void EdgeInsertion::set_has_time() {
  _has_bits_[0] |= 0x00000020u;
}
inline void EdgeInsertion::clear_has_time() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void EdgeInsertion::clear_time() {
  time_ = GOOGLE_LONGLONG(1);
  clear_has_time();
}
inline ::google::protobuf::int64 EdgeInsertion::time() const {
  return time_;
}
inline void EdgeInsertion::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// EdgeDeletion

// optional int64 source = 1 [default = 0];
inline bool EdgeDeletion::has_source() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EdgeDeletion::set_has_source() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EdgeDeletion::clear_has_source() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EdgeDeletion::clear_source() {
  source_ = GOOGLE_LONGLONG(0);
  clear_has_source();
}
inline ::google::protobuf::int64 EdgeDeletion::source() const {
  return source_;
}
inline void EdgeDeletion::set_source(::google::protobuf::int64 value) {
  set_has_source();
  source_ = value;
}

// optional string source_str = 2 [default = ""];
inline bool EdgeDeletion::has_source_str() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EdgeDeletion::set_has_source_str() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EdgeDeletion::clear_has_source_str() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EdgeDeletion::clear_source_str() {
  if (source_str_ != &::google::protobuf::internal::kEmptyString) {
    source_str_->clear();
  }
  clear_has_source_str();
}
inline const ::std::string& EdgeDeletion::source_str() const {
  return *source_str_;
}
inline void EdgeDeletion::set_source_str(const ::std::string& value) {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  source_str_->assign(value);
}
inline void EdgeDeletion::set_source_str(const char* value) {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  source_str_->assign(value);
}
inline void EdgeDeletion::set_source_str(const char* value, size_t size) {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  source_str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EdgeDeletion::mutable_source_str() {
  set_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    source_str_ = new ::std::string;
  }
  return source_str_;
}
inline ::std::string* EdgeDeletion::release_source_str() {
  clear_has_source_str();
  if (source_str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = source_str_;
    source_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void EdgeDeletion::set_allocated_source_str(::std::string* source_str) {
  if (source_str_ != &::google::protobuf::internal::kEmptyString) {
    delete source_str_;
  }
  if (source_str) {
    set_has_source_str();
    source_str_ = source_str;
  } else {
    clear_has_source_str();
    source_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int64 destination = 3 [default = 1];
inline bool EdgeDeletion::has_destination() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void EdgeDeletion::set_has_destination() {
  _has_bits_[0] |= 0x00000004u;
}
inline void EdgeDeletion::clear_has_destination() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void EdgeDeletion::clear_destination() {
  destination_ = GOOGLE_LONGLONG(1);
  clear_has_destination();
}
inline ::google::protobuf::int64 EdgeDeletion::destination() const {
  return destination_;
}
inline void EdgeDeletion::set_destination(::google::protobuf::int64 value) {
  set_has_destination();
  destination_ = value;
}

// optional string destination_str = 4 [default = ""];
inline bool EdgeDeletion::has_destination_str() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void EdgeDeletion::set_has_destination_str() {
  _has_bits_[0] |= 0x00000008u;
}
inline void EdgeDeletion::clear_has_destination_str() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void EdgeDeletion::clear_destination_str() {
  if (destination_str_ != &::google::protobuf::internal::kEmptyString) {
    destination_str_->clear();
  }
  clear_has_destination_str();
}
inline const ::std::string& EdgeDeletion::destination_str() const {
  return *destination_str_;
}
inline void EdgeDeletion::set_destination_str(const ::std::string& value) {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  destination_str_->assign(value);
}
inline void EdgeDeletion::set_destination_str(const char* value) {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  destination_str_->assign(value);
}
inline void EdgeDeletion::set_destination_str(const char* value, size_t size) {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  destination_str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* EdgeDeletion::mutable_destination_str() {
  set_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    destination_str_ = new ::std::string;
  }
  return destination_str_;
}
inline ::std::string* EdgeDeletion::release_destination_str() {
  clear_has_destination_str();
  if (destination_str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = destination_str_;
    destination_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void EdgeDeletion::set_allocated_destination_str(::std::string* destination_str) {
  if (destination_str_ != &::google::protobuf::internal::kEmptyString) {
    delete destination_str_;
  }
  if (destination_str) {
    set_has_destination_str();
    destination_str_ = destination_str;
  } else {
    clear_has_destination_str();
    destination_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// StingerBatch

// optional int64 version = 1 [default = 1];
inline bool StingerBatch::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StingerBatch::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StingerBatch::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StingerBatch::clear_version() {
  version_ = GOOGLE_LONGLONG(1);
  clear_has_version();
}
inline ::google::protobuf::int64 StingerBatch::version() const {
  return version_;
}
inline void StingerBatch::set_version(::google::protobuf::int64 value) {
  set_has_version();
  version_ = value;
}

// repeated .gt.stinger.EdgeInsertion insertions = 3;
inline int StingerBatch::insertions_size() const {
  return insertions_.size();
}
inline void StingerBatch::clear_insertions() {
  insertions_.Clear();
}
inline const ::gt::stinger::EdgeInsertion& StingerBatch::insertions(int index) const {
  return insertions_.Get(index);
}
inline ::gt::stinger::EdgeInsertion* StingerBatch::mutable_insertions(int index) {
  return insertions_.Mutable(index);
}
inline ::gt::stinger::EdgeInsertion* StingerBatch::add_insertions() {
  return insertions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeInsertion >&
StingerBatch::insertions() const {
  return insertions_;
}
inline ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeInsertion >*
StingerBatch::mutable_insertions() {
  return &insertions_;
}

// repeated .gt.stinger.EdgeDeletion deletions = 4;
inline int StingerBatch::deletions_size() const {
  return deletions_.size();
}
inline void StingerBatch::clear_deletions() {
  deletions_.Clear();
}
inline const ::gt::stinger::EdgeDeletion& StingerBatch::deletions(int index) const {
  return deletions_.Get(index);
}
inline ::gt::stinger::EdgeDeletion* StingerBatch::mutable_deletions(int index) {
  return deletions_.Mutable(index);
}
inline ::gt::stinger::EdgeDeletion* StingerBatch::add_deletions() {
  return deletions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeDeletion >&
StingerBatch::deletions() const {
  return deletions_;
}
inline ::google::protobuf::RepeatedPtrField< ::gt::stinger::EdgeDeletion >*
StingerBatch::mutable_deletions() {
  return &deletions_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace stinger
}  // namespace gt

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_src_2fproto_2fstinger_2dbatch_2eproto__INCLUDED
